from .controller import (
    ActivationBottleneckController,
    apply_activation_bottleneck,
    parse_placements,
    resolve_layers,
)
from .gate import AdaptiveLapSumTopKGate, validate_gate_shapes
from .lapsum import (
    lapsum_barrier_bisect,
    lapsum_barrier_sorted,
    lapsum_budget,
    lapsum_probs,
    lapsum_probs_at,
    laplace_cdf,
    laplace_pdf,
)
from .module import SparseTopKBottleneck
from .jumprelu import (default_log_theta, jumprelu_count,
                       jumprelu_forward, rect_kernel)
from .rblapsum import GRAD_MODES as RBLAPSUM_GRAD_MODES
from .rblapsum import rblapsum_gate
from .reinforce import (DISTRIBUTIONS as REINFORCE_DISTRIBUTIONS,
                        conditional_bernoulli_sample, gumbel_pl_sample,
                        pl_score_from_order, sample_exact_k)
from .swap import swap_gibbs_mask, swap_log_rho, swap_probs, swap_weights
from .temperature import (
    STATUS_ABOVE_RANGE,
    STATUS_BELOW_RANGE,
    STATUS_DEGENERATE,
    STATUS_NAMES,
    STATUS_OK,
    effective_count,
    gradient_count,
    gradient_weights,
    score_softmax_count,
    solve_joint_temperature,
    solve_reference_temperature,
    solve_score_softmax_temperature,
    status_fractions,
)

__all__ = [
    "ActivationBottleneckController",
    "apply_activation_bottleneck",
    "resolve_layers",
    "parse_placements",
    "SparseTopKBottleneck",
    "AdaptiveLapSumTopKGate",
    "validate_gate_shapes",
    "laplace_cdf",
    "laplace_pdf",
    "lapsum_probs",
    "lapsum_probs_at",
    "lapsum_budget",
    "lapsum_barrier_sorted",
    "lapsum_barrier_bisect",
    "RBLAPSUM_GRAD_MODES",
    "REINFORCE_DISTRIBUTIONS",
    "conditional_bernoulli_sample",
    "gumbel_pl_sample",
    "pl_score_from_order",
    "sample_exact_k",
    "rblapsum_gate",
    "default_log_theta",
    "jumprelu_count",
    "jumprelu_forward",
    "rect_kernel",
    "swap_gibbs_mask",
    "swap_log_rho",
    "swap_probs",
    "swap_weights",
    "effective_count",
    "score_softmax_count",
    "gradient_count",
    "gradient_weights",
    "solve_score_softmax_temperature",
    "solve_joint_temperature",
    "solve_reference_temperature",
    "status_fractions",
    "STATUS_OK",
    "STATUS_BELOW_RANGE",
    "STATUS_ABOVE_RANGE",
    "STATUS_DEGENERATE",
    "STATUS_NAMES",
]
